package org.cthul.parser.lexer;

import org.cthul.parser.api.Context;
import org.cthul.parser.api.Input;
import org.cthul.parser.api.StringInput;

/**
 * 
 * @param <I> input that is produced
 */
public interface Lexer<I extends Input<?>> {
    
//    /**
//     * @return matchers for the tokens generated by this lexer.
//     */
//    List<InputMatcher<? super I>> getTokenMatchers();
    
    I scan(Context<StringInput> context);
    
}
