package org.cthul.matchers.testold;

import org.hamcrest.Matcher;
import org.hamcrest.Matchers;

/**
 * Classes like this are generated by Factory annotations.
 * They are the starting point of custom fluent generation.
 * 
 * @author Arian Treffer
 */
public class ColorMatchers {
    
    public static Matcher<String> red() {
        return Matchers.containsString("red");
    }
    
    public static Matcher<String> green() {
        return Matchers.containsString("green");
    }
    
    public static Matcher<String> blue() {
        return Matchers.containsString("blue");
    }
    
    public static Matcher<Integer> black() {
        return Matchers.equalTo(0);
    }
    
}
