package org.cthul.matchers.test;

import java.util.List;
import org.cthul.matchers.ContainsPattern;
import org.hamcrest.Matcher;
import org.hamcrest.Matchers;

/**
 * Classes like this are generated by Factory annotations.
 * They are the starting point of custom fluent generation.
 * 
 * @author Arian Treffer
 */
public class ColorMatchers {
    
    public static Matcher<String> red() {
        return Matchers.containsString("red");
    }
    
//    public static Matcher<String> green() {
//        return Matchers.containsString("green");
//    }
//    
//    public static Matcher<String> blue() {
//        return Matchers.containsString("blue");
//    }
    
    public static Matcher<Integer> black() {
        return Matchers.equalTo(0);
    }
    
    public static <T> Matcher<T> stuff(List<Integer> ints) {
        return null;
    }
    
    public static <T> Matcher<T> stuff(String name) {
        return null;
    }
    
    public static <T extends Throwable> Matcher<T> stuff2(T t) {
        return null;
    }
    
    public static ContainsPattern gray() {
        return new ContainsPattern("gray");
    }
    
}
